import PokeredBugs.Proofs.FocusEnergy
import PokeredBugs.Proofs.BlaineAI
import PokeredBugs.Proofs.OneIn256
import PokeredBugs.Proofs.PsywaveDesync
import PokeredBugs.Proofs.StatScaling
import PokeredBugs.Proofs.AccEvaCancel
import PokeredBugs.Proofs.ReflectOverflow
import PokeredBugs.Proofs.BadgeReflect
import PokeredBugs.Proofs.Substitute
