import SM83

namespace AutoResearch

/--
In Pokemon Red/Blue, accuracy and critical hit checks compare a random byte
generated by the internal RNG against a threshold byte. 

The bug is that the game uses a "strictly less than" comparison (`roll < threshold`)
instead of a "less than or equal" comparison (`roll <= threshold`).
-/
def impl (threshold : BitVec 8) (roll : BitVec 8) : Bool :=
  roll < threshold

/--
The intended behavior is that a move with an accuracy byte of 255 (representing 255/255, or 100%)
should hit regardless of the random roll generated (which is in the range 0-255).
This requires the inclusion of the case where the roll equals the threshold.
-/
def spec (threshold : BitVec 8) (roll : BitVec 8) : Bool :=
  roll <= threshold

/-- 
L1: Concrete witness of the 1/256 miss bug. 
For a move with "100%" accuracy (threshold 255), a specific RNG roll of 255 
will cause a miss in the buggy implementation while hitting in the specification.
-/
theorem exists_1in256_miss : ∃ (roll : BitVec 8), impl 255 roll = false ∧ spec 255 roll = true := by
  -- The witness is the maximum byte value
  exists 255
  simp [impl, spec]
  -- 255 < 255 is false; 255 <= 255 is true
  native_decide

/-- 
L2: Universal characterization.
The implementation and specification differ if and only if the roll exactly 
matches the threshold value. This identifies the "1 in 256" case for any threshold.
-/
theorem bug_iff_roll_matches_threshold (t r : BitVec 8) : (impl t r ≠ spec t r) ↔ (r = t) := by
  have h := (by native_decide : ∀ (t' r' : BitVec 8), (r' < t' ≠ r' <= t') ↔ (r' = t'))
  exact h t r

/-- 
L3: A fix for the bug. 
By replacing the strictly-less-than check with a less-than-or-equal check, 
the behavior matches the intended specification.
-/
def fix (t r : BitVec 8) : Bool := r <= t

theorem fix_is_correct : ∀ t r, fix t r = spec t r := by
  intro t r; rfl

/-- 
L4: Relational Divergence - Perfection.
In the specification, a move with accuracy 255 (100%) will never miss, 
no matter what value the RNG produces.
-/
theorem spec_100_percent_accuracy_always_hits : ∀ (roll : BitVec 8), spec 255 roll = true := by
  have h := (by native_decide : ∀ (r : BitVec 8), r <= 255 = true)
  exact h

/-- 
L4: Relational Divergence - The "1 in 256" property.
In the buggy implementation, for a 100% accuracy move, there exists exactly 
one roll (255) that causes the move to miss.
-/
theorem impl_100_percent_accuracy_only_misses_on_255 : ∀ (roll : BitVec 8), impl 255 roll = false ↔ roll = 255 := by
  have h := (by native_decide : ∀ (r : BitVec 8), (r < 255 = false) ↔ (r = 255))
  exact h

/--
L4: Relational Consistency.
The buggy implementation never incorrectly "hits" when the specification 
would "miss"; it only ever incorrectly misses.
-/
theorem impl_is_always_pessimistic : ∀ (t r : BitVec 8), impl t r = true → spec t r = true := by
  have h := (by native_decide : ∀ (t' r' : BitVec 8), (r' < t' = true) → (r' <= t' = true))
  exact h

end AutoResearch
