import SM83

/-!
# Bug #3: Blaine's AI Uses Super Potion Regardless of HP

## Description
In Pokémon Red/Blue, Blaine (the Cinnabar Island Gym Leader) has a unique bug in 
his AI routine. Unlike other trainers who use healing items, Blaine's AI does 
not call `AICheckIfHPBelowFraction`. This means he will use a Super Potion 
whenever a random 25% roll succeeds, even if his Pokémon is at full HP.

## Formalization
We model the AI logic using the provided assembly.
- `blaineAI`: Implements the logic found in the `BlaineAI` label.
- `saneAI`: Implements what a typical healing AI does (roll + HP check).
-/

namespace AutoResearch

/-- 
High-level model of the Battle State relevant to Blaine's AI. 
-/
structure BattleState where
  /-- Random value (0-255) generated by the game engine before AI routines. -/
  roll  : BitVec 8
  /-- Current HP of Blaine's Active Pokémon. -/
  curHP : BitVec 16
  /-- Maximum HP of Blaine's Active Pokémon. -/
  maxHP : BitVec 16

/--
`AICheckIfHPBelowFraction` from assembly.
Returns true (carry) if current HP < maxHP / divisor.
-/
def AICheckIfHPBelowFraction (hp maxHP : BitVec 16) (divisor : Nat) : Bool :=
  hp.toNat * divisor < maxHP.toNat

/--
Blaine's actual AI logic (Buggy).
Assembly:
  cp 25 percent + 1 ; 25 percent + 1 = 64
  ret nc            ; If roll >= 64, exit
  jp AIUseSuperPotion
-/
def blaineAI (s : BattleState) : Bool :=
  s.roll < 64

/--
The intended/correct AI logic for a healing item.
A "sane" AI checks both the probability roll AND whether HP is low.
Typical healers use a divisor of 2 (50% HP) or 4 (25% HP).
-/
def saneAI (s : BattleState) : Bool :=
  (s.roll < 64) && (AICheckIfHPBelowFraction s.curHP s.maxHP 2)

---

### L1: Bug Existence
We prove there exists a state where Blaine wastes a turn using a potion 
at full HP, while a sane AI would not.

theorem bug_exists : ∃ s, s.curHP = s.maxHP ∧ s.maxHP > 0 ∧ blaineAI s = true ∧ saneAI s = false := by
  -- Witness: Roll is 0 (passes 25% check), HP is 100/100.
  let s : BattleState := { roll := 0, curHP := 100, maxHP := 100 }
  exists s
  simp [blaineAI, saneAI, AICheckIfHPBelowFraction]
  native_decide

---

### L2: Characterization
We prove exactly when the bug triggers: the bug occurs whenever the random roll 
succeeds (roll < 64) but the Pokémon's HP is not below the required threshold 
(HP >= MaxHP/2).

theorem bug_trigger_condition (s : BattleState) :
  blaineAI s ≠ saneAI s ↔ (s.roll < 64) ∧ ¬(AICheckIfHPBelowFraction s.curHP s.maxHP 2) := by
  simp [blaineAI, saneAI]
  -- Truth table logic: (A ≠ (A ∧ B)) ↔ (A ∧ ¬B)
  cases Decidable.decide (s.roll < 64) with
  | isTrue h => 
    simp [h]
  | isFalse h => 
    simp [h]

---

### L3: Fix Correctness
We define a fixed version of Blaine's AI that correctly checks HP before 
using the potion, and prove it matches our specification.

def blaineFix (s : BattleState) : Bool :=
  if s.roll < 64 then
    -- Add the missing call to AICheckIfHPBelowFraction
    AICheckIfHPBelowFraction s.curHP s.maxHP 2
  else
    false

theorem fix_matches_spec (s : BattleState) : blaineFix s = saneAI s := by
  unfold blaineFix saneAI
  split <;> simp [*]

---

### L4: Behavioral Divergence
We prove that Blaine's AI is completely independent of his Pokémon's 
actual HP, which is the core of the logical error.

theorem blaine_ai_ignores_hp (roll : BitVec 8) (hp1 hp2 maxHP : BitVec 16) :
  blaineAI ⟨roll, hp1, maxHP⟩ = blaineAI ⟨roll, hp2, maxHP⟩ := by
  -- The function definition does not reference hp1 or hp2
  simp [blaineAI]

theorem sane_ai_depends_on_hp : 
  ∃ roll maxHP hp_low hp_high, 
    saneAI ⟨roll, hp_low, maxHP⟩ = true ∧ 
    saneAI ⟨roll, hp_high, maxHP⟩ = false := by
  -- At roll 0, sane AI heals at 10 HP but not at 100 HP (max 100)
  exists 0, 100, 10, 100
  simp [saneAI, AICheckIfHPBelowFraction]
  native_decide

end AutoResearch
